/**
 * Top 50 popular games — card metadata only.
 * Quiz packs: js/quests/data/<id>.js (hasQuest: true).
 */
window.gamesCatalog = [
    // ——— With quizzes (16) ———
    {
        id: 'minecraft',
        title: 'Minecraft',
        gameName: 'Minecraft',
        subtitle: 'Minecraft Quiz',
        emoji: '⛏️',
        image: 'img/quests/minecraft.jpg',
        section: 'trending',
        featured: 1,
        showcaseSize: 'big',
        showcaseTag: 'Sandbox · Mojang',
        mode: 'solo',
        duration: 'short',
        type: 'story',
        durationLabel: '10 min',
        hasQuest: true,
        favDesc: 'Boundless sandbox',
    },
    {
        id: 'fortnite',
        title: 'Fortnite',
        gameName: 'Fortnite',
        subtitle: 'Fortnite Quiz',
        image: 'img/quests/fortnite.jpg',
        emoji: '🪂',
        section: 'trending',
        featured: 2,
        showcaseSize: 'small',
        showcaseTag: 'Battle Royale · Epic',
        mode: 'coop',
        duration: 'short',
        type: 'daily',
        durationLabel: '10 min',
        hasQuest: true,
        favDesc: 'Build, shoot, survive',
    },
    {
        id: 'gta5',
        title: 'GTA V',
        gameName: 'Grand Theft Auto V',
        subtitle: 'GTA V Quiz',
        image: 'img/quests/gta5.jpg',
        emoji: '🚗',
        section: 'trending',
        featured: 3,
        showcaseSize: 'small',
        showcaseTag: 'Action · Rockstar',
        mode: 'coop',
        duration: 'long',
        type: 'story',
        durationLabel: '20 min',
        hasQuest: true,
        favDesc: 'Los Santos chaos',
    },
    {
        id: 'roblox',
        title: 'Roblox',
        gameName: 'Roblox',
        subtitle: 'Roblox Quiz',
        image: 'img/quests/roblox.jpg',
        emoji: '🧱',
        section: 'trending',
        featured: 4,
        showcaseSize: 'wide',
        showcaseTag: 'Platform · Roblox Corp',
        mode: 'coop',
        duration: 'short',
        type: 'daily',
        durationLabel: '10 min',
        hasQuest: true,
        favDesc: 'Millions of worlds',
    },
    {
        id: 'league-of-legends',
        title: 'League of Legends',
        gameName: 'League of Legends',
        subtitle: 'LoL Quiz',
        image: 'img/quests/league-of-legends.jpg',
        emoji: '⚔️',
        section: 'trending',
        featured: 5,
        showcaseTag: 'MOBA · Riot',
        mode: 'coop',
        duration: 'medium',
        type: 'daily',
        durationLabel: '15 min',
        hasQuest: true,
        favDesc: 'Summoners Rift',
    },
    {
        id: 'valorant',
        title: 'Valorant',
        gameName: 'Valorant',
        subtitle: 'Valorant Quiz',
        image: 'img/quests/valorant.jpg',
        emoji: '🎯',
        section: 'trending',
        featured: 6,
        showcaseTag: 'Tactical FPS · Riot',
        mode: 'coop',
        duration: 'short',
        type: 'daily',
        durationLabel: '10 min',
        hasQuest: true,
        favDesc: 'Agents and abilities',
    },
    {
        id: 'cs2',
        title: 'Counter-Strike 2',
        gameName: 'Counter-Strike 2',
        subtitle: 'CS2 Quiz',
        emoji: '🔫',
        image: 'img/quests/cs2.jpg',
        section: 'trending',
        featured: 7,
        showcaseTag: 'Shooter · Valve',
        mode: 'solo',
        duration: 'short',
        type: 'story',
        durationLabel: '10 min',
        hasQuest: true,
        favDesc: 'Tactical shooter',
    },
    {
        id: 'genshin-impact',
        title: 'Genshin Impact',
        gameName: 'Genshin Impact',
        subtitle: 'Genshin Quiz',
        image: 'img/quests/genshin-impact.jpg',
        emoji: '✨',
        section: 'trending',
        featured: 8,
        showcaseTag: 'Action RPG · miHoYo',
        mode: 'solo',
        duration: 'medium',
        type: 'daily',
        durationLabel: '15 min',
        hasQuest: true,
        favDesc: 'Teyvat exploration',
    },
    {
        id: 'elden-ring',
        title: 'Elden Ring',
        gameName: 'Elden Ring',
        subtitle: 'Elden Ring Quiz',
        image: 'img/quests/elden-ring.jpg',
        emoji: '⚜️',
        section: 'trending',
        featured: 9,
        showcaseTag: 'Soulslike · FromSoftware',
        mode: 'solo',
        duration: 'long',
        type: 'story',
        durationLabel: '20 min',
        hasQuest: true,
        favDesc: 'Open-world Souls',
    },
    {
        id: 'baldurs-gate-3',
        title: "Baldur's Gate 3",
        gameName: "Baldur's Gate 3",
        subtitle: 'BG3 Quiz',
        image: 'img/quests/baldurs-gate-3.jpg',
        emoji: '🎲',
        section: 'trending',
        featured: 10,
        showcaseTag: 'CRPG · Larian',
        mode: 'coop',
        duration: 'long',
        type: 'story',
        durationLabel: '25 min',
        hasQuest: true,
        favDesc: 'D&D in Faerûn',
    },
    {
        id: 'hogwarts-legacy',
        title: 'Hogwarts Legacy',
        gameName: 'Hogwarts Legacy',
        subtitle: 'Hogwarts Quiz',
        image: 'img/quests/hogwarts-legacy.jpg',
        emoji: '🪄',
        section: 'trending',
        featured: 11,
        showcaseTag: 'Action RPG · Avalanche',
        mode: 'solo',
        duration: 'medium',
        type: 'story',
        durationLabel: '15 min',
        hasQuest: false,
        favDesc: 'Wizarding world',
    },
    {
        id: 'witcher3',
        title: 'Photo Hunt',
        gameName: 'The Witcher 3',
        subtitle: 'The Witcher 3 Quiz',
        emoji: '🏹',
        image: 'img/quests/witcher3.jpg',
        section: 'trending',
        featured: 12,
        showcaseTag: 'RPG · CD Projekt Red',
        mode: 'solo',
        duration: 'medium',
        type: 'daily',
        durationLabel: '10 min',
        hasQuest: true,
        favDesc: 'Dark fantasy with choices',
    },
    {
        id: 'cyberpunk',
        title: 'City Secrets',
        gameName: 'Cyberpunk 2077',
        subtitle: 'Cyberpunk 2077 Quiz',
        emoji: '🌃',
        image: 'img/quests/cyberpunk.jpg',
        section: 'trending',
        featured: 13,
        showcaseTag: 'RPG · CD Projekt Red',
        mode: 'solo',
        duration: 'medium',
        type: 'story',
        durationLabel: '30 min',
        hasQuest: true,
        favDesc: 'Open world of Night City',
    },
    {
        id: 'apex-legends',
        title: 'Apex Legends',
        gameName: 'Apex Legends',
        subtitle: 'Apex Quiz',
        image: 'img/quests/apex-legends.jpg',
        emoji: '🏃',
        section: 'trending',
        featured: 14,
        showcaseTag: 'Battle Royale · Respawn',
        mode: 'coop',
        duration: 'short',
        type: 'daily',
        durationLabel: '10 min',
        hasQuest: false,
        favDesc: 'Legends never die',
    },
    {
        id: 'helldivers-2',
        title: 'Helldivers 2',
        gameName: 'Helldivers 2',
        subtitle: 'Helldivers Quiz',
        image: 'img/quests/helldivers-2.jpg',
        emoji: '🪖',
        section: 'trending',
        featured: 15,
        showcaseTag: 'Co-op Shooter · Arrowhead',
        mode: 'coop',
        duration: 'medium',
        type: 'daily',
        durationLabel: '12 min',
        hasQuest: false,
        favDesc: 'Spread democracy',
    },
    {
        id: 'palworld',
        title: 'Palworld',
        gameName: 'Palworld',
        subtitle: 'Palworld Quiz',
        image: 'img/quests/palworld.jpg',
        emoji: '🐾',
        section: 'trending',
        featured: 16,
        showcaseTag: 'Survival · Pocketpair',
        mode: 'coop',
        duration: 'medium',
        type: 'story',
        durationLabel: '15 min',
        hasQuest: false,
        favDesc: 'Pals and crafting',
    },
    {
        id: 'dota2',
        title: 'Dota 2',
        gameName: 'Dota 2',
        subtitle: 'Dota 2 Quiz',
        image: 'img/quests/dota2.jpg',
        emoji: '🛡️',
        section: 'trending',
        featured: 17,
        showcaseTag: 'MOBA · Valve',
        mode: 'coop',
        duration: 'long',
        type: 'daily',
        durationLabel: '20 min',
        hasQuest: false,
        favDesc: 'Ancient defense',
    },
    {
        id: 'overwatch2',
        title: 'Overwatch 2',
        gameName: 'Overwatch 2',
        subtitle: 'Overwatch Quiz',
        image: 'img/quests/overwatch2.jpg',
        emoji: '🦸',
        section: 'trending',
        featured: 18,
        showcaseTag: 'Hero Shooter · Blizzard',
        mode: 'coop',
        duration: 'short',
        type: 'daily',
        durationLabel: '10 min',
        hasQuest: false,
        favDesc: 'Heroes united',
    },
    {
        id: 'skyrim',
        title: 'Review Marathon',
        gameName: 'Skyrim',
        subtitle: 'Skyrim Quiz',
        emoji: '🐉',
        image: 'img/quests/skyrim.jpg',
        section: 'trending',
        featured: 19,
        showcaseTag: 'RPG · Bethesda',
        mode: 'coop',
        duration: 'medium',
        type: 'daily',
        durationLabel: '15 min',
        hasQuest: true,
        favDesc: 'Dragons and adventure',
    },
    {
        id: 'rocket-league',
        title: 'Rocket League',
        gameName: 'Rocket League',
        subtitle: 'Rocket League Quiz',
        emoji: '🚗',
        image: 'img/quests/rocket-league.jpg',
        section: 'trending',
        featured: 20,
        showcaseTag: 'Sports · Psyonix',
        mode: 'coop',
        duration: 'short',
        type: 'story',
        durationLabel: '10 min',
        hasQuest: true,
        favDesc: 'Soccer with cars',
    },
    {
        id: 'among-us',
        title: 'Among Us',
        gameName: 'Among Us',
        subtitle: 'Among Us Quiz',
        image: 'img/quests/among-us.jpg',
        emoji: '👽',
        section: 'trending',
        featured: 21,
        showcaseTag: 'Party · Innersloth',
        mode: 'coop',
        duration: 'short',
        type: 'daily',
        durationLabel: '8 min',
        hasQuest: false,
        favDesc: 'Find the impostor',
    },
    {
        id: 'call-of-duty',
        title: 'Call of Duty',
        gameName: 'Call of Duty: Warzone',
        subtitle: 'CoD Quiz',
        image: 'img/quests/call-of-duty.jpg',
        emoji: '💣',
        section: 'trending',
        featured: 22,
        showcaseTag: 'FPS · Activision',
        mode: 'coop',
        duration: 'short',
        type: 'daily',
        durationLabel: '10 min',
        hasQuest: false,
        favDesc: 'Warzone and DMZ',
    },
    {
        id: 'pokemon-scarlet',
        title: 'Pokémon Scarlet',
        gameName: 'Pokémon Scarlet & Violet',
        subtitle: 'Pokémon Quiz',
        image: 'img/quests/pokemon-scarlet.jpg',
        emoji: '⚡',
        section: 'trending',
        featured: 23,
        showcaseTag: 'RPG · Game Freak',
        mode: 'solo',
        duration: 'medium',
        type: 'story',
        durationLabel: '15 min',
        hasQuest: false,
        favDesc: 'Catch em all',
    },
    {
        id: 'mario-odyssey',
        title: 'Super Mario Odyssey',
        gameName: 'Super Mario Odyssey',
        subtitle: 'Mario Quiz',
        image: 'img/quests/mario-odyssey.jpg',
        emoji: '🍄',
        section: 'trending',
        featured: 24,
        showcaseTag: 'Platformer · Nintendo',
        mode: 'solo',
        duration: 'short',
        type: 'story',
        durationLabel: '10 min',
        hasQuest: false,
        favDesc: 'Cappy adventures',
    },
    {
        id: 'zelda-totk',
        title: 'Zelda: TOTK',
        gameName: 'The Legend of Zelda: Tears of the Kingdom',
        subtitle: 'Zelda Quiz',
        image: 'img/quests/zelda-totk.jpg',
        emoji: '🗡️',
        section: 'trending',
        featured: 25,
        showcaseTag: 'Adventure · Nintendo',
        mode: 'solo',
        duration: 'long',
        type: 'story',
        durationLabel: '20 min',
        hasQuest: false,
        favDesc: 'Hyrule skies and depths',
    },

    // ——— Popular (25) ———
    {
        id: 'rdr2',
        title: 'Red Dead 2',
        gameName: 'Red Dead Redemption 2',
        subtitle: 'RDR2 Quiz',
        image: 'img/quests/rdr2.jpg',
        emoji: '🤠',
        section: 'popular',
        featured: 26,
        showcaseTag: 'Western · Rockstar',
        mode: 'solo',
        duration: 'long',
        type: 'story',
        durationLabel: '25 min',
        hasQuest: false,
        favDesc: 'Wild West epic',
    },
    {
        id: 'fallout-4',
        title: 'Fallout 4',
        gameName: 'Fallout 4',
        subtitle: 'Fallout Quiz',
        image: 'img/quests/fallout-4.jpg',
        emoji: '☢️',
        section: 'popular',
        featured: 27,
        showcaseTag: 'RPG · Bethesda',
        mode: 'solo',
        duration: 'medium',
        type: 'story',
        durationLabel: '15 min',
        hasQuest: false,
        favDesc: 'Wasteland survival',
    },
    {
        id: 'dark-souls-3',
        title: 'Dark Souls III',
        gameName: 'Dark Souls III',
        subtitle: 'Dark Souls Quiz',
        image: 'img/quests/dark-souls-3.jpg',
        emoji: '🔥',
        section: 'popular',
        featured: 28,
        showcaseTag: 'Soulslike · FromSoftware',
        mode: 'solo',
        duration: 'medium',
        type: 'story',
        durationLabel: '15 min',
        hasQuest: false,
        favDesc: 'Prepare to die',
    },
    {
        id: 'sekiro',
        title: 'Sekiro',
        gameName: 'Sekiro: Shadows Die Twice',
        subtitle: 'Sekiro Quiz',
        image: 'img/quests/sekiro.jpg',
        emoji: '🥷',
        section: 'popular',
        featured: 29,
        showcaseTag: 'Action · FromSoftware',
        mode: 'solo',
        duration: 'medium',
        type: 'story',
        durationLabel: '15 min',
        hasQuest: false,
        favDesc: 'Shinobi revenge',
    },
    {
        id: 'god-of-war',
        title: 'God of War',
        gameName: 'God of War Ragnarök',
        subtitle: 'God of War Quiz',
        image: 'img/quests/god-of-war.jpg',
        emoji: '🪓',
        section: 'popular',
        featured: 30,
        showcaseTag: 'Action · Santa Monica',
        mode: 'solo',
        duration: 'medium',
        type: 'story',
        durationLabel: '18 min',
        hasQuest: false,
        favDesc: 'Kratos and Atreus',
    },
    {
        id: 'spider-man',
        title: 'Spider-Man',
        gameName: "Marvel's Spider-Man",
        subtitle: 'Spider-Man Quiz',
        image: 'img/quests/spider-man.jpg',
        emoji: '🕷️',
        section: 'popular',
        featured: 31,
        showcaseTag: 'Action · Insomniac',
        mode: 'solo',
        duration: 'medium',
        type: 'story',
        durationLabel: '15 min',
        hasQuest: false,
        favDesc: 'Web-slinging NYC',
    },
    {
        id: 'resident-evil-4',
        title: 'Resident Evil 4',
        gameName: 'Resident Evil 4',
        subtitle: 'RE4 Quiz',
        image: 'img/quests/resident-evil-4.jpg',
        emoji: '🧟',
        section: 'popular',
        featured: 32,
        showcaseTag: 'Horror · Capcom',
        mode: 'solo',
        duration: 'medium',
        type: 'story',
        durationLabel: '15 min',
        hasQuest: false,
        favDesc: 'Survival horror classic',
    },
    {
        id: 'last-of-us',
        title: 'The Last of Us',
        gameName: 'The Last of Us Part II',
        subtitle: 'TLOU Quiz',
        image: 'img/quests/last-of-us.jpg',
        emoji: '🌿',
        section: 'popular',
        featured: 33,
        showcaseTag: 'Action · Naughty Dog',
        mode: 'solo',
        duration: 'long',
        type: 'story',
        durationLabel: '20 min',
        hasQuest: false,
        favDesc: 'Post-apocalypse drama',
    },
    {
        id: 'horizon-zero-dawn',
        title: 'Horizon',
        gameName: 'Horizon Zero Dawn',
        subtitle: 'Horizon Quiz',
        image: 'img/quests/horizon-zero-dawn.jpg',
        emoji: '🏹',
        section: 'popular',
        featured: 34,
        showcaseTag: 'Action RPG · Guerrilla',
        mode: 'solo',
        duration: 'medium',
        type: 'story',
        durationLabel: '15 min',
        hasQuest: false,
        favDesc: 'Machines and tribes',
    },
    {
        id: 'hollow-knight',
        title: 'Hollow Knight',
        gameName: 'Hollow Knight',
        subtitle: 'Hollow Knight Quiz',
        image: 'img/quests/hollow-knight.jpg',
        emoji: '🦋',
        section: 'popular',
        featured: 35,
        showcaseTag: 'Metroidvania · Team Cherry',
        mode: 'solo',
        duration: 'medium',
        type: 'story',
        durationLabel: '12 min',
        hasQuest: false,
        favDesc: 'Hallownest depths',
    },
    {
        id: 'hades',
        title: 'Hades',
        gameName: 'Hades',
        subtitle: 'Hades Quiz',
        image: 'img/quests/hades.jpg',
        emoji: '💀',
        section: 'popular',
        featured: 36,
        showcaseTag: 'Roguelike · Supergiant',
        mode: 'solo',
        duration: 'short',
        type: 'story',
        durationLabel: '10 min',
        hasQuest: false,
        favDesc: 'Escape the underworld',
    },
    {
        id: 'stardew-valley',
        title: 'Stardew Valley',
        gameName: 'Stardew Valley',
        subtitle: 'Stardew Quiz',
        image: 'img/quests/stardew-valley.jpg',
        emoji: '🌾',
        section: 'popular',
        featured: 37,
        showcaseTag: 'Farming · ConcernedApe',
        mode: 'solo',
        duration: 'short',
        type: 'story',
        durationLabel: '10 min',
        hasQuest: false,
        favDesc: 'Cozy farm life',
    },
    {
        id: 'terraria',
        title: 'Terraria',
        gameName: 'Terraria',
        subtitle: 'Terraria Quiz',
        image: 'img/quests/terraria.jpg',
        emoji: '⛏️',
        section: 'popular',
        featured: 38,
        showcaseTag: 'Sandbox · Re-Logic',
        mode: 'coop',
        duration: 'medium',
        type: 'story',
        durationLabel: '12 min',
        hasQuest: false,
        favDesc: 'Dig, fight, explore',
    },
    {
        id: 'portal-2',
        title: 'Portal 2',
        gameName: 'Portal 2',
        subtitle: 'Portal Quiz',
        image: 'img/quests/portal-2.jpg',
        emoji: '🌀',
        section: 'popular',
        featured: 39,
        showcaseTag: 'Puzzle · Valve',
        mode: 'coop',
        duration: 'short',
        type: 'story',
        durationLabel: '10 min',
        hasQuest: false,
        favDesc: 'Thinking with portals',
    },
    {
        id: 'team-fortress-2',
        title: 'Team Fortress 2',
        gameName: 'Team Fortress 2',
        subtitle: 'TF2 Quiz',
        image: 'img/quests/team-fortress-2.jpg',
        emoji: '🎩',
        section: 'popular',
        featured: 40,
        showcaseTag: 'Shooter · Valve',
        mode: 'coop',
        duration: 'short',
        type: 'daily',
        durationLabel: '10 min',
        hasQuest: false,
        favDesc: 'Meet the classes',
    },
    {
        id: 'half-life-alyx',
        title: 'Half-Life: Alyx',
        gameName: 'Half-Life: Alyx',
        subtitle: 'Half-Life: Alyx Quiz',
        emoji: '🥽',
        image: 'img/quests/half-life-alyx.jpg',
        section: 'popular',
        featured: 41,
        showcaseTag: 'VR Shooter · Valve',
        mode: 'solo',
        duration: 'medium',
        type: 'story',
        durationLabel: '15 min',
        hasQuest: true,
        favDesc: 'VR masterpiece from Valve',
    },
    {
        id: 'doom-eternal',
        title: 'DOOM Eternal',
        gameName: 'DOOM Eternal',
        subtitle: 'DOOM Quiz',
        image: 'img/quests/doom-eternal.jpg',
        emoji: '😈',
        section: 'popular',
        featured: 42,
        showcaseTag: 'FPS · id Software',
        mode: 'solo',
        duration: 'short',
        type: 'story',
        durationLabel: '10 min',
        hasQuest: false,
        favDesc: 'Rip and tear',
    },
    {
        id: 'diablo-4',
        title: 'Diablo IV',
        gameName: 'Diablo IV',
        subtitle: 'Diablo Quiz',
        image: 'img/quests/diablo-4.jpg',
        emoji: '🔱',
        section: 'popular',
        featured: 43,
        showcaseTag: 'ARPG · Blizzard',
        mode: 'coop',
        duration: 'medium',
        type: 'story',
        durationLabel: '15 min',
        hasQuest: false,
        favDesc: 'Sanctuary darkness',
    },
    {
        id: 'starfield',
        title: 'Starfield',
        gameName: 'Starfield',
        subtitle: 'Starfield Quiz',
        image: 'img/quests/starfield.jpg',
        emoji: '🚀',
        section: 'popular',
        featured: 44,
        showcaseTag: 'RPG · Bethesda',
        mode: 'solo',
        duration: 'long',
        type: 'story',
        durationLabel: '20 min',
        hasQuest: false,
        favDesc: 'Settled among the stars',
    },
    {
        id: 'mass-effect',
        title: 'Mass Effect',
        gameName: 'Mass Effect Legendary Edition',
        subtitle: 'Mass Effect Quiz',
        image: 'img/quests/mass-effect.jpg',
        emoji: '🛸',
        section: 'popular',
        featured: 45,
        showcaseTag: 'Sci-Fi RPG · BioWare',
        mode: 'solo',
        duration: 'long',
        type: 'story',
        durationLabel: '20 min',
        hasQuest: false,
        favDesc: 'Commander Shepard saga',
    },
    {
        id: 'ff7-remake',
        title: 'FF VII Remake',
        gameName: 'Final Fantasy VII Remake',
        subtitle: 'FF7 Quiz',
        image: 'img/quests/ff7-remake.jpg',
        emoji: '⚔️',
        section: 'popular',
        featured: 46,
        showcaseTag: 'JRPG · Square Enix',
        mode: 'solo',
        duration: 'long',
        type: 'story',
        durationLabel: '18 min',
        hasQuest: false,
        favDesc: 'Midgar reborn',
    },
    {
        id: 'persona-5',
        title: 'Persona 5',
        gameName: 'Persona 5 Royal',
        subtitle: 'Persona Quiz',
        image: 'img/quests/persona-5.jpg',
        emoji: '🎭',
        section: 'popular',
        featured: 47,
        showcaseTag: 'JRPG · Atlus',
        mode: 'solo',
        duration: 'long',
        type: 'story',
        durationLabel: '20 min',
        hasQuest: false,
        favDesc: 'Phantom thieves',
    },
    {
        id: 'forza-horizon-5',
        title: 'Forza Horizon 5',
        gameName: 'Forza Horizon 5',
        subtitle: 'Forza Quiz',
        image: 'img/quests/forza-horizon-5.jpg',
        emoji: '🏎️',
        section: 'popular',
        featured: 48,
        showcaseTag: 'Racing · Playground',
        mode: 'coop',
        duration: 'short',
        type: 'daily',
        durationLabel: '10 min',
        hasQuest: false,
        favDesc: 'Mexico open world',
    },
    {
        id: 'rust',
        title: 'Rust',
        gameName: 'Rust',
        subtitle: 'Rust Quiz',
        image: 'img/quests/rust.jpg',
        emoji: '🏚️',
        section: 'popular',
        featured: 49,
        showcaseTag: 'Survival · Facepunch',
        mode: 'coop',
        duration: 'long',
        type: 'daily',
        durationLabel: '15 min',
        hasQuest: false,
        favDesc: 'Trust no one',
    },
    {
        id: 'ac-mirage',
        title: 'AC: Mirage',
        gameName: "Assassin's Creed: Mirage",
        subtitle: 'AC: Mirage Quiz',
        emoji: '🗡️',
        image: 'img/quests/ac-mirage.jpg',
        section: 'popular',
        featured: 50,
        showcaseTag: 'Stealth · Ubisoft',
        mode: 'solo',
        duration: 'short',
        type: 'story',
        durationLabel: '12 min',
        hasQuest: true,
        favDesc: 'Return to the roots',
    },
];
